### ISSUE TITLE
[Bug]: Issue with repeated queries when loading prezet.index

### ISSUE THREAD

**Issue by kyledoesdev** [benbjurstrom/prezet#100]
### What happened?

Hi there, I am new to prezet and really like it so far but could use some help. Whenever I load /prezet or prezet.index, the debug bar is showing that several queries were executed, like 100+! I removed a lot of the sample articles and that helped a lot but it still fires 50+ queries and it takes the page several seconds to load.

I made sure to run ```php artisan prezet:index ```. I am assuming I am just doing something wrong caching wise maybe. I can see in the sqlite field that the data is there too.

### How to reproduce the bug

![data](https://github.com/user-attachments/assets/65876a37-08bc-4c6b-b9da-6b1a10d0d2a6)
![queries](https://github.com/user-attachments/assets/68ce113b-23b2-425b-af25-458c4ad1a817)

### Package Version

0.18.0

### PHP Version

8.3.0

### Laravel Version

11.31

### Which operating systems does with happen with?

Windows 11

**Comment by benbjurstrom** [comment]
Appreciate the report. Looks like the issue is the index being automatically refreshed on each page load when running locally. Once I removed that block the queries dropped to only 2.

https://github.com/benbjurstrom/prezet/blob/62f5e773e73dbb3d1cdba6c9628798f557f680ac/src/Http/Controllers/IndexController.php#L11-L17

I added that code to aid in development so I wouldn't have to run `php artisan prezet:index` every time I made a change, but I can see why that would be slow if you have a lot of articles.

I'll add something to the config so you can turn that off. In the meantime you want to remove it you can just override the index controller. This article explains how to do that. https://prezet.com/customize/controllers

**Comment by benbjurstrom** [comment]
Ended up removing the index on page load and setup vite to watch for changes to the prezet folder instead. This will only occur when running `npm run dev` and since the `vite.config.js` file lives in user space the feature can be easily removed.
